### ISSUE TITLE
Newbiew Question!

### ISSUE THREAD

**Issue by KostasC22** [springinpractice/sip01#3]
Hello I am little confused how to import this projects on the Spring Tool Suite! I don't know how! Can you help me, please?

**Comment by SebMace** [comment]
In Eclipse --> Import --> Existing Maven Project --> Choose your pom

**Comment by uttamjaiswal86** [comment]
Hi all, First of thanks for all you have done. I got stuck while implementing p name space with jdbcAccountDao. There is one method called getAll which threw Exception called UnSupportedOperationException. Now when we inject accoutDao from our applicationConfig.xml then we are providing jdbcAccountDao class implementation and from consoleApp; we are calling getAll of jdbcAccountDao. how this code is working ?? 

I am getting this stack below. Am I missing somethings ?

INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@16d8356: defining beans [org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0,accountService,accountDao,dataSource]; root of factory hierarchy
Exception in thread "main" java.lang.UnsupportedOperationException: This method has not been implemented.
    at com.spring.in.glow.ch01.dao.jdbc.JdbcAccountDao.getAll(JdbcAccountDao.java:19)
    at com.spring.in.glow.ch01.service.AccountService.findDelinquentAccounts(AccountService.java:25)
    at com.spring.in.glow.ch01.ConsoleApp.main(ConsoleApp.java:17)
